dodona-edu/universal-judge

judge/src/tested/judge/execution.py

Use hardlink for selector instead of copy

---

judge/src/tested/languages/kotlin/templates/value_basic.mako

Remove to much whitespace kotlin, fix #58

---

tested/judge/execution.py
tested/judge/programmed.py
tested/languages/config.py
tested/languages/kotlin/config.py

Fix IndexError by return Compilation Error Status

---

tested/languages/config.py
tests/test_utils.py

Add compiler stdout and stderr output limit

---

tested/languages/c/config.py

Cleanup c compiler output

---

tested/languages/config.py
tested/languages/generator.py
tested/languages/haskell/config.py
tested/languages/javascript/config.py

Remove implicit namespace from haskell and javascript exercises

---

tested/judge/compilation.py
tested/judge/core.py
tested/judge/execution.py
tested/languages/c/config.py
tested/languages/config.py
tested/languages/kotlin/config.py
tested/languages/python/config.py
tested/languages/utils.py

Cleanup Kotlin Compiler stacktrace

---

tested/judge/compilation.py
tested/languages/config.py
tested/languages/python/config.py

Fix python stdout html link

---

.gitignore
tested/languages/kotlin/config.py
tested/languages/python/config.py
tested/languages/python/templates/values.py
tested/manual.py

Fix python exception message
Keep kotlin whitespace when rewriting main header for stacktrace line numbers

Some fixes

---

tested/serialisation.py

Possible cause of error: using sequences as function arguments

Fix empty filter object

---

tested/judge/evaluation.py
tested/testplan.py

Add simple file link list

---

tested/languages/python/config.py

No compiler warnings python

---

README.md
tested/evaluators/__init__.py
tested/evaluators/nothing.py
tested/judge/evaluation.py
tests/test_functionality.py

Runtime error when getting unexpected exception

---

tested/judge/evaluation.py

Indicate timeout in test

---

tested/judge/collector.py

Add output fix

---

.github/workflows/ci.yml

Eventually we should look into caching the aeson build, as that takes 5 minutes.

Re-enable haskell tests

---

tested/internationalization/en.yaml
tested/internationalization/nl.yaml
tested/judge/collector.py
tested/judge/core.py

Fix feedback output

---

exercise/objects/evaluation/no-test.yaml
requirements.txt
tested/judge/evaluation.py
tested/languages/generator.py
tested/testplan.py

Inline file links

---

tested/languages/generator.py

Cleaner HTML expression descriptions

---

tested/languages/config.py
tested/languages/generator.py
tested/languages/python/config.py

Support different text quotes

---

exercise/objects/evaluation/no-test.yaml
tested/serialisation.py
tested/utils.py

Fix bugs evaluation set and map

---

tested/description_instance.py
tested/instantiate_exercise.py

Add script to create full instances of a template exercise

Instantiate template exercise

---

exercise/counter/config.json
exercise/counter/evaluation/plan.yaml
exercise/counter/solution/solution.java
exercise/counter/solution/solution.js
exercise/counter/solution/solution.kt
exercise/counter/solution/solution.py
tested/manual.py
tests/test_functionality.py

Add tests void functions

---

.github/workflows/ci.yml
docker/dodona-tested.dockerfile
exercise/counter/solution/solution-checkstyle.java
exercise/counter/solution/solution-eslint.js
exercise/counter/solution/solution-pylint.py
exercise/echo-function/solution/correct-cppcheck.c
lgtm.yml
pytest.ini
tested/configs.py
tested/internationalization/en.yaml
tested/internationalization/nl.yaml
tested/languages/c/config.py
tested/languages/c/linter.py
tested/languages/haskell/config.py
tested/languages/haskell/hlint.yml
tested/languages/haskell/linter.py
tested/languages/java/config.py
tested/languages/java/linter.py
tested/languages/java/sun_tested_checks.xml
tested/languages/javascript/config.py
tested/languages/javascript/eslintrc.yml
tested/languages/javascript/linter.py
tested/languages/kotlin/config.py
tested/languages/kotlin/linter.py
tested/languages/runhaskell/config.py
tested/manual.py
tests/manual_utils.py
tests/test_linters.py

Add linters

---

tested/judge/evaluation.py

Apply suggestion of @pdawyndt 
close #182

Use message to indicate not executed context

---

tested/languages/c/linter.py
tested/languages/haskell/linter.py
tested/languages/java/linter.py
tested/languages/javascript/linter.py
tested/languages/kotlin/linter.py
tested/languages/python/linter.py

close #186
Handle non-existing keys in linters objects.

Bug linters

---

tested/languages/kotlin/config.py
tests/test_functionality.py

Add staff messages to find the problems with Kotlin compiler, see #117.

Add staff messages for the Kotlin compiler stdout and stderr

---

tested/languages/kotlin/linter.py

Change severity level KTLint to INFO

---

tested/judge/core.py
tests/test_functionality.py

Hide (pre)compilation tab when compilation succeeded

---

exercise/echo-function/evaluation/one-nested.yaml
tested/dsl/grammar.lark
tested/manual.py
tested/serialisation.py
tests/test_functionality.py

Nested function calls didn't work.
This PR solve this problem.

Fix nested function calls

---

exercise/sum/solution/correct.sh
tested/languages/bash/config.json
tested/languages/bash/templates/run.sh
tested/languages/bash/templates/value.mako
tests/test_functionality.py

Forgot reduced support for a single character in BASH

Bash Char reduced

---

tested/datatypes/__init__.py
tested/datatypes/advanced.py
tested/languages/bash/config.json
tested/languages/c/config.json
tested/languages/haskell/config.json
tested/languages/java/config.json
tested/languages/javascript/config.json
tested/languages/javascript/templates/value.mako
tested/languages/javascript/templates/values.js
tested/languages/python/config.json
tested/languages/runhaskell/config.json
tests/test_serialisation.py

Support undefined

---

tested/utils.py
tests/test_utils.py

Rewrite timsort

---

exercise/echo-function-file/config.json
exercise/echo-function-file/description/description.en.md
exercise/echo-function-file/description/description.nl.md
exercise/echo-function-file/evaluation/one.tson
exercise/echo-function-file/solution/correct.c
exercise/echo-function-file/solution/correct.hs
exercise/echo-function-file/solution/correct.java
exercise/echo-function-file/solution/correct.js
exercise/echo-function-file/solution/correct.kt
exercise/echo-function-file/solution/correct.py
exercise/echo-function-file/solution/correct.sh
exercise/echo-function-file/workdir/data.txt
tested/dsl/translate_parser.py
tested/judge/evaluation.py
tested/languages/generator.py
tested/testplan.py
tests/test_functionality.py

Remove file url fields

---

.github/workflows/ci.yml
exercise/echo/solution/comp-error.js
exercise/echo/solution/comp-error.sh
tested/judge/compilation.py
tested/judge/programmed.py
tested/languages/bash/config.py
tested/languages/c/config.py
tested/languages/config.py
tested/languages/haskell/config.py
tested/languages/javascript/config.py
tested/languages/kotlin/config.py
tested/languages/python/config.py
tested/languages/runhaskell/config.py
tests/test_functionality.py

Use the compilation step to check the syntax of the no-compilation languages.
close #214

Syntax check no compilation languages

---

tested/evaluators/exception.py

Don't fail on not given exception

---

dsl-examples/dsl-full.yaml
tested/dsl/schema.yaml
tested/dsl/translate_parser.py
tests/test_dsl_yaml.py

Consistent camelCase in DSL

---

docker/dodona-tested.dockerfile
tested/internationalization/en.yaml
tested/internationalization/nl.yaml
tested/languages/bash/linter.py
tested/languages/haskell/linter.py
tested/languages/java/linter.py
tested/languages/javascript/linter.py
tested/languages/kotlin/linter.py
tested/languages/python/linter.py

close #210 for now
But the suggestion (https://github.com/dodona-edu/universal-judge/issues/210#issuecomment-823868678) of Niko is a better alternative.

Add more information links for the linter messages

---

tested/judge/execution.py

Fix not showing timeout

---

tested/languages/kotlin/config.py

Reduce memory kotlin compiler

---

exercise/echo-function/evaluation/one-display-multiline.tson
exercise/echo-function/evaluation/one-display-no-multiline.tson
tested/dsl/translate_parser.py
tested/evaluators/__init__.py
tested/evaluators/value.py
tested/judge/evaluation.py
tests/test_functionality.py

Display or escape newlines in feedback

---

tested/languages/kotlin/config.py
tests/test_functionality.py

Remove kotlin compiler output.
Only merge after solving #117.

Remove stdout and stderr messages from kotlin compiler

---

.github/workflows/ci.yml
README.md
docker/dodona-tested.dockerfile
tested/internationalization/en.yaml
tested/internationalization/nl.yaml
tested/languages/java/linter.py
tested/languages/kotlin/linter.py

Remove JARS from repo

---

tested/languages/generator.py

Message code

---

tested/configs.py
tested/manual.py
tests/manual_utils.py
tests/test_linters.py

Update linter configuration

---

exercise/js-exceptions/config.json
exercise/js-exceptions/evaluation/plan.yaml
exercise/js-exceptions/solution/correct.js
exercise/js-exceptions/solution/wrong-message.js
exercise/js-exceptions/solution/wrong.js
tested/evaluators/exception.py
tested/internationalization/en.yaml
tested/internationalization/nl.yaml
tested/languages/javascript/templates/values.js
tested/serialisation.py
tests/test_functionality.py

Add JavaScript support for only proper exceptions

---

benchmarking/__init__.py
exercise/isbn-list/preparation/generator.py
exercise/isbn/preparation/generator.py
tested/configs.py
tested/instantiate_exercise.py
tested/main.py
tests/manual_utils.py
tests/test_functionality.py

Rename 'plan_name' to 'testplan'

---

tested/judge/evaluation.py

Fix duplicate message time limit exceeded

---

.github/workflows/ci.yml
docker/dodona-tested.dockerfile
requirements.txt
tested/languages/javascript/config.py
tested/languages/javascript/eslintrc.yml
tested/languages/javascript/parseAst.js

Use `abstract-syntax-tree` javascript module which supports ECMA2020.
close #257

New version JavaScript AST Parser

---

tested/languages/javascript/config.py
tested/languages/javascript/parseAst.js
tests/testJavascriptAstParserFile.js
tests/test_utils.py

Support static variables and other new javascript features.

Improve AST parse

---

exercise/echo-function-file/solution/correct-async.js
exercise/echo-function/solution/correct-async.js
tested/languages/javascript/templates/evaluatorExecutor.mako
tested/languages/javascript/templates/function.mako
tested/languages/javascript/templates/run.mako
tested/languages/javascript/templates/statement.mako
tested/languages/javascript/templates/value_arguments.mako
tested/languages/javascript/templates/value_basic.mako
tests/testJavascriptAstParserFile.js
tests/test_functionality.py
tests/test_utils.py

Remove redundant `await`'s in the generate JavaScript code

---

exercise/echo-function-additional-source-files/config.json
exercise/echo-function-additional-source-files/description/description.en.md
exercise/echo-function-additional-source-files/description/description.nl.md
exercise/echo-function-additional-source-files/evaluation/full.tson
exercise/echo-function-additional-source-files/evaluation/one.tson
exercise/echo-function-additional-source-files/solution/correct.c
exercise/echo-function-additional-source-files/solution/correct.hs
exercise/echo-function-additional-source-files/solution/correct.java
exercise/echo-function-additional-source-files/solution/correct.js
exercise/echo-function-additional-source-files/solution/correct.kt
exercise/echo-function-additional-source-files/solution/correct.py
exercise/echo-function-additional-source-files/solution/correct.sh
exercise/echo-function-additional-source-files/workdir/Echo.hs
exercise/echo-function-additional-source-files/workdir/Echo.java
exercise/echo-function-additional-source-files/workdir/Echo.kt
exercise/echo-function-additional-source-files/workdir/echo.c
exercise/echo-function-additional-source-files/workdir/echo.h
exercise/echo-function-additional-source-files/workdir/echo.js
exercise/echo-function-additional-source-files/workdir/echo.py
exercise/echo-function-additional-source-files/workdir/echo.sh
tested/judge/core.py
tested/languages/c/config.py
tested/languages/config.py
tests/test_functionality.py

Copy additional source files from workdir on batch compilation

---

tested/evaluators/text.py

Fix textual floating point comparing of zero values.

Fix compare textual floating point zero

---

.github/workflows/ci.yml

Should also probably update the dockerfile at some point.

Fix CI by upgrading GHC

---

tested/configs.py

Re-add default value for test suites

---

.github/workflows/ci.yml
requirements-test.txt

Add codecov integration

---

tested/evaluators/value.py
tested/languages/javascript/config.py
tests/test_stacktrace_cleaners.py

Fixes #346.
Before:
```
Traceback:AssertionError [ERR_ASSERTION]: ongeldig bericht
at <code>:86:13
<code>:98
at <code>:98:18
```
After:
```
Traceback:AssertionError [ERR_ASSERTION]: ongeldig bericht
at bigram2letter (<code>:86:13)
at <code>:98:32
at Array.map (<anonymous>)
at Codeersleutel.decodeer (<code>:98:18)
```

Improve JavaScript stacktraces

---

tested/evaluators/exception.py
tested/internationalization/en.yaml
tested/internationalization/nl.yaml
tested/languages/javascript/templates/values.js
tested/serialisation.py
tests/test_evaluators.py
tests/test_functionality.py

Re-add an error message when a non-Error is thrown in JavaScript.

Improve error messages for non-Errors in js

---

tested/languages/python/linter.py

Stolen from https://github.com/dodona-edu/judge-pythia/commit/6a8b21748861bb5f48680dd5e2ffd3eb744461b4

Prevent negative cols in pylint

---

flake.lock
flake.nix
flake.old.nix
tested/evaluators/value.py
tested/languages/bash/generators.py
tested/languages/c/generators.py
tested/languages/csharp/generators.py
tested/languages/haskell/generators.py
tested/languages/java/generators.py
tested/languages/javascript/generators.py
tested/languages/kotlin/generators.py
tested/languages/python/generators.py
tested/languages/utils.py
tested/serialisation.py

Fix nested unknown types

---

tested/languages/javascript/templates/values.js

Forgot to push a change in #380 :(
See for example Tab 1 in https://dodona.ugent.be/en/submissions/14252910/

Fix null comparison in JavaScript

---

tested/languages/javascript/config.py
tested/languages/kotlin/config.py
tested/languages/python/config.py

Fixes #354, see that issue for more details and context.

Enable strict mode in JavaScript

---

flake.lock
flake.nix
tested/dsl/schema.json
tested/dsl/translate_parser.py
tested/languages/preparation.py
tested/testsuite.py
tests/exercises/echo-function/evaluation/one-no-return.yaml
tests/exercises/objects/evaluation/missing_key_types.yaml
tests/test_dsl_yaml.py
tests/test_functionality.py

Reverts dodona-edu/universal-judge#374. This was merged prematurely.

Revert "Don't ignore return value if return is "none""

---

tests/test_functionality.py

Done while investigating #395, but no other work was necessary.

Improve a test

---

tested/dsl/__main__.py
tested/dsl/translate_parser.py
tested/main.py
tests/test_dsl_yaml.py

Improve invalid DSL errors

---

tested/dsl/schema.json
tested/dsl/schema_draft7.json
tested/dsl/translate_parser.py
tests/exercises/objects/evaluation/missing_key_types.yaml
tests/exercises/objects/evaluation/no-test.yaml
tests/test_dsl_yaml.py

This will catch more errors explicitly.
Fixes #416.

Disallow additional properties in DSL

---

tested/languages/generation.py

Don't prefix file URLs with media/

---

tested/languages/javascript/config.py

Fix line numbers in JavaScript

---

tested/dodona.py
tested/dsl/ast_translator.py
tested/dsl/schema.json
tested/dsl/schema_draft7.json
tested/dsl/translate_parser.py
tested/languages/generation.py
tested/languages/javascript/generators.py
tested/testsuite.py
tests/exercises/global/evaluation/plan.yaml

- Better error messages in a bunch of cases
- Support setting a custom description of testcases

Various small improvements

---

tested/dodona.py
tested/judge/core.py
tested/languages/config.py
tested/languages/python/config.py

This outputs metadata for the Python Tutor in Dodona for Python.
Files are not yet handled, as those will be in a follow up PR (both here and in Dodona).
Do not merge before https://github.com/dodona-edu/dodona/pull/5050, otherwise the output format will be invalid.
Fixes #448.

Support Dodona debug information

---

tested/judge/core.py

Only provide debug info for supported languages

---

tested/languages/python/generators.py
tests/exercises/echo/solution/input-prompt.py
tests/test_functionality.py

Ignore "input" prompt in Python

---

tested/oracles/value.py
tests/test_oracles.py

Fix bug in value comparator

---

tested/oracles/value.py
tested/serialisation.py
tested/utils.py
tests/test_utils.py

Fixes e.g. https://dodona.be/nl/submissions/18144981/, https://dodona.be/nl/submissions/18146122/.

Fix bug in set comparisons

---

tested/languages/javascript/templates/values.js
tests/exercises/echo-function/evaluation/javascript-object.yaml
tests/exercises/echo-function/solution/javascript-object.js
tests/test_functionality.py

Support "vanilla" JS objects

---

flake.nix

Actually run all tests in CI
