- tested/judge/compilation.py
- tested/manual.py
A weird Haskell error still occurs (https://dodona.ugent.be/en/submissions/5952347/). Some investigating reveals:
- When a compilation error occurs in batch mode, Tested switches to individual compilation by default.
- When each context is being compiled in Haskell, this is very slow.
- Tested has a global timeout, which will be triggered in the individual mode with Haskell.
- This means that sometimes the compilation process is killed due to a timeout.
- When the compilation process is killed, the exit code is still 0.
- The code only checked for timeout errors if the compilation exit code was not 0.
(This might also be the cause of #68, perhaps we should try to revert parts of #70 later (since it will now hide unexpected errors).)
> Fix weird compilation errors

- tested/languages/java/templates/Values.java
- tested/languages/kotlin/templates/Values.kt
Example fault:
```json
{
"type": "unknown",
"data": kotlin.Unit
}
```
Fix:
```json
{
"type": "unknown",
"data": "kotlin.Unit"
}
```
> Fix wrong JSON encoding unknown type Kotlin and Java

- tested/dodona.py
- tested/judge/evaluation.py
Some fixes for not executed testcases, see #114.
- Only message at context level.
- When context has no description, use message as description.
Add pseudo status `NOT_EXECUTED` is currently equal to the status `wrong` at Dodona.
> First fixes for not executed testcases

- exercise/isbn/evaluation/one-with-crashing-assignment-java.tson
- exercise/isbn/evaluation/one-with-crashing-assignment-kotlin.tson
- exercise/objects/evaluation/plan.tson
- tested/languages/generator.py
- tested/languages/haskell/templates/function.mako
- tested/languages/java/templates/function.mako
- tested/languages/javascript/templates/function.mako
- tested/languages/kotlin/templates/function.mako
- tested/languages/python/templates/function.mako
- tested/serialisation.py
Remove `NAMESPACE` function call type, because it can be repressented by the `FUNCTION` type and a given namespace, which is more intuitive.
close #144
> Namespaces

- tested/dsl/statement.py
- tested/languages/python/templates/value_basic.mako
- tests/test_dsl_expression.py
Fix incorrect formatting of escaped characters in DSL and python.
- Escaping must not be done in DSL.
- Example fixed problem python:
Wanted/given in testplan:
```python
\"
```
Generated:
```python
\\\"
```
> Fix escape string DSL

- .github/workflows/ci.yml
- descriptions/demo.md.mako
- descriptions/erfgenaam.md.mako
- descriptions/spoorhekcodering.html.mako
- tested/description_instance.py
- tested/generation/types.json
- tested/languages/bash/types.json
- tested/languages/c/types.json
- tested/languages/description_generator.py
- tested/languages/haskell/types.json
- tested/languages/java/types.json
- tested/languages/javascript/types.json
- tested/languages/kotlin/types.json
- tested/languages/python/types.json
- tests/test_utils.py
Apply some suggestions of @pdawyndt for the template descriptions.
1. Add _plural_ forms for the natural type names.
2. Remove the constant `namespace_html`.
3. `namespace` will be adopted to the Markdown/HTML Context
4. Remove the constant `language_html`.
5. `language` is renamed to `programming_language` and will be adopted to the Markdown/HTML Context.
6. `programming_language_for_condition` contains always the unescaped programming language string.
7. The function `natural_type_name` is extended with a second parameter `plural` with default value `false`.
8. Add the constant `natural_language` contains the natural name of the natural language, with the `iso639-1` code as fallback.
9. Add the constant `natural_language_iso639` contains the `iso639-1` language code for the natural …
> Update description generator variables and functions

- tests/test_utils.py
Add a test to validate the YAML and JSON files of the judge, to avoid problems if they can't be parsed correctly.
> Add test to validate YAML and JSON files

- tested/dsl/statement.py
- tested/dsl/tested.lark
- tests/test_dsl_expression.py
Update the parser for the micro-programminglanguage from **early** to **lalr(1)**.
Therefor the grammar rules are also updated to be non-ambigue.
This has a speedup from  _6.796 s_ to _0.390 s_ for parsing the statements and expressions of the [Star Battle](https://dodona.ugent.be/nl/courses/453/series/4862/activities/39590992/submissions/) exercise, which is approximated 17 times faster.
> Update DSL statement parser

- tested/languages/java/templates/value_basic.mako
Change the default decimal value notation in Java from `float` to `double`.
> Fix java default decimal value to double instead of float

- tested/languages/java/templates/value_basic.mako
Java `Map.of()` has a maximum of 10 entries.
To support more entries, I changed it to `Map.ofEntries()`.
> Fix Java map with more than 10 entries

- tested/evaluators/text.py
- tests/test_evaluators.py
Avoid confusion (from the actual values) when comparing the values **caseInsensitive** and **ignoreWhitespace** when showing the results.
> Hotfix: text evaluator:  fix actual values that are modified by the comparision options

- exercise/echo/solution/correct.py
- exercise/echo/solution/warning.sh
- tested/dodona.py
- tested/languages/bash/linter.py
- tested/languages/haskell/linter.py
- tested/languages/java/linter.py
- tested/languages/javascript/linter.py
- tested/languages/kotlin/linter.py
- tested/languages/python/linter.py
- tests/test_linters.py
Adds support for `externalUrl` in the linter messages where possible.
Fixes #286, as linter messages no longer contain HTML.
Superseeds #294, as this re-implements it on top of the black formatting changes.
> Add support for externalUrl in linter messages

- tested/languages/generator.py
- Honour namespace setting in display
- Escape arguments properly
> Improve command line argument display

- exercise/sum/solution/non-utf8-output.sh
- tested/judge/utils.py
- tests/test_utils.py
The processes that run the generated executable are executed using `subprocess.run()`. By default, the output streams (e.g. stdout, stderr) are assumed to be in utf-8, using the "strict" mode. This means invalid utf8 in the output streams causes the judge to crash.
The fix is to enable the "backslashreplace" mode, which replaces invalid sequences by a backslash-escaped version.
See https://docs.python.org/3/library/io.html#io.TextIOWrapper.
Also adds a test for this issue.
> Properly handle invalid utf8 in output streams

- tested/languages/generator.py
We always use the same character, since this is "just" a program execution, meaning it is always the same.
Closes #308.
> Add prompt to main calls

- tested/languages/generator.py
Instead of the generic "code", format it as "console", which should provide better highlighting.
> Apply console syntax highlighting on main calls

- tested/languages/description_generator.py
- tested/languages/generator.py
Since we do syntax highlighting ourselves when there are files, we need to actually use the console highlighter. Additionally, disable wrapping of the output, so we don't need to slice the resulting HTML.
> Properly apply console syntax highlighting

- tested/configs.py
- tested/languages/c/config.py
- tested/languages/haskell/config.py
- tested/languages/kotlin/config.py
Add config option to enable compiler optimisations, currently available for C, Haskell and Kotlin.
Fixes #292.
> Add an option to enable compiler optimisations

- tested/configs.py
- tested/languages/bash/linter.py
- tested/languages/c/linter.py
- tested/languages/haskell/linter.py
- tested/languages/java/linter.py
- tested/languages/javascript/linter.py
- tested/languages/kotlin/linter.py
- tested/languages/python/linter.py
Support the `rows` and `columns` property in annotations for those linters that support it. We ignored these parameters, Dodona didn't do anything with them, but this will probably change in the future.
Also fix a line offset bug when using the shebang.
Related: https://github.com/dodona-edu/dodona/pull/4568
> Support multiline and multicolumn linters

- tested/judge/execution.py
- tests/test_functionality.py
Time limit exceeded (or memory limit exceeded in theory) were not propagated to the results properly if a submissions was executed in one go.
This PR fixes this and adds a test for it.
Fixes an underlying issue of #342.
> Fix status propagation

- tested/languages/javascript/eslintrc.yml
- tested/languages/javascript/linter.py
- Fixes #345, by supporting the latest JS version
- Fixes #344, by enabling the semicolon rule
- Fixes #348 (reported in #347), by fixing a bug in how ESLint results were parsed
> Various ESLint improvements

- tested/languages/python/pylint_config.rc
This check results in many false positives, especially since a lot of problem statements give a one-letter name to variables. Additionally, some exercises use camel-case.
Fixes #351.
> Sync Pylint with Python judge

- tested/languages/javascript/templates/values.js
- tests/exercises/js-exceptions/solution/correct-temp.js
- tests/exercises/js-exceptions/solution/wrong-null.js
- tests/test_functionality.py
We don't want to change this behaviour in the middle of the course, but after this semester, we will remove this special case.
For example: https://dodona.ugent.be/nl/submissions/14015216.
> Re-allow plain JS objects as exceptions

- tested/evaluators/value.py
- tests/test_evaluators.py
Our support for pretty printing multiline strings was too late in the process: if there was no actual value, we returned early, before the multiline pretty printing was applied.
By moving the multiline pretty printing support to the front, we should cover all cases.
Fixes #368.
> Pretty print multiline string if no actual value

- tested/internationalization/en.yaml
- tested/internationalization/nl.yaml
- tested/judge/compilation.py
- tested/languages/javascript/config.py
- tests/test_stacktrace_cleaners.py
- The message indicating where the error was produced has been removed (for all languages).
- The JavaScript stacktrace cleaning has been improved to add `<code>` links in compiler stacktraces.
Fixes #366
> Improve (JS) compiler output

- tested/languages/python/pylint_config.rc
Fixes #375 
(Ignore the commit message, I accidentally first pushed this to master directly, which I then reverted)
> Disable C0303 in Pylint

- tested/datatypes/advanced.py
- tested/evaluators/value.py
- tested/languages/c/config.py
- tested/languages/config.py
- tested/languages/csharp/config.py
- tested/languages/haskell/config.py
- tested/languages/java/config.py
- tested/languages/javascript/config.py
- tested/languages/kotlin/config.py
- tested/languages/python/config.py
This allows us to enforce "null" in JavaScript, without accepting "undefined".
This is pretty JavaScript-specific, but so is the "undefined" type, and one of the desired features of the whole basic/advanced system is to support cases like this.
For example, to enforce `null` and not ` undefined` in the DSL, you must cast the value (otherwise both `null` and `undefined` will be accepted):
```yaml
- tab: "Test tab"
testcases:
- expression: 'some_function()'
return_raw: 'null(None)'
```
> Support advanced "null" type

- tested/languages/utils.py
As mentioned in #121, this isn't that useful.
Fixes #121.
> Remove "Traceback:" from output

- tested/languages/utils.py
- tests/test_stacktrace_cleaners.py
Stacktraces were no linger linked to the code. This due to the regex not using escaped HTML characters, while it was applied after the stacktrace is already escaped.
Fixes #387.
> Fix linked stacktraces

- tested/dsl/ast_translator.py
- tests/test_dsl_yaml.py
Allows the use of our "cast" functions without arguments to represent "empty" values. This allows writing `set()` instead of `set([])`, which should be more intuitive for those familiar with Python.
This is currently support for "sequence" types, i.e. `set`, `sequence`, `array`, `tuple`, and "map" types, i.e. `map`.
Fixes #385.
> Support empty constructors

- flake.lock
- tested/dsl/schema.json
- tested/dsl/translate_parser.py
- tested/testsuite.py
- tests/test_dsl_yaml.py
This adds support for custom checks in the DSL:
```yaml
- tab: 'Test'
contexts:
- testcases:
- statement: 'test()'
return_raw:
value: "'hallo'"
evaluator: "custom"
language: "python"
file: "test.py"
name: "evaluate_test"
arguments: ["'yes'", "5", "set([5, 5])"]
```
As a reminder, custom checks are available for textual output (e.g. stdout, stderr) and return values. For return values, only `return_raw` is supported (not `return`, as we cannot know if an object is a value or a custom check).
Fixes #391.
> Add support for custom checks in DSL

- tested/evaluators/value.py
- tested/serialisation.py
- tests/test_evaluators.py
In adding the types, we used `zip_longest`, which resulted in a crash if there were more values than expected in the test suite. This has been fixed to properly handle this.
> Fix crash and add test

- .github/workflows/ci.yml
- tested/dsl/ast_translator.py
- tested/dsl/schema.json
- tested/dsl/translate_parser.py
- tests/test_dsl_yaml.py
This PR adds support for YAML tags in the DSL.
- We support the standard YAML `!!set` (fixes #401)
- We support all TESTed types via "local data types", meaning with a single exclamation mark: `!int64`, `!set`, ... (fixes #402)
For example:
```yaml
- tab: 'Test'
contexts:
- testcases:
- statement: 'test()'
return: !!set {5, 6}
```
Note that the return statement is not checked by the JSON Schema (as it is not capable of doing custom types), so if you put nonsense, it will crash with an exception somewhere (e.g. `!int64 [5, 6]` will result in a crash).
> Support YAML tags

- tested/languages/javascript/templates/values.js
- tested/oracles/value.py
We didn't handle "holes" in JS arrays.
For example, https://dodona.be/en/submissions/14641782/.
> Fix crash in JS

- tested/configs.py
- tested/descriptions/__init__.py
- tested/dsl/schema.json
- tested/dsl/translate_parser.py
- tested/features.py
- tested/internationalization/en.yaml
- tested/internationalization/nl.yaml
- tested/judge/evaluation.py
- tested/languages/__init__.py
- tested/languages/c/generators.py
- tested/languages/csharp/generators.py
- tested/languages/generation.py
- tested/languages/haskell/generators.py
- tested/languages/java/generators.py
- tested/languages/preparation.py
- tested/manual.py
- tested/serialisation.py
- tested/testsuite.py
- tested/utils.py
- tests/exercises/echo-function/evaluation/one-language-literals.yaml
- tests/exercises/echo-function/solution/correct.c
- tests/exercises/echo-function/solution/correct.cs
- tests/exercises/echo-function/solution/correct.hs
- tests/exercises/echo-function/solution/correct.java
- tests/exercises/echo-function/solution/correct.js
- tests/exercises/echo-function/solution/correct.kt
- tests/exercises/echo-function/solution/correct.py
- tests/exercises/echo-function/solution/correct.sh
- tests/test_dsl_yaml.py
- tests/test_functionality.py
Fixes #399.
As mentioned in the issue, you do need to be aware if you need to namespace function calls for each language or not. For example:
```yaml
- tab: "My tab"
testcases:
- expression:
c: "to_string(1+1)"
haskell: "Submission.toString (1+1)"
runhaskell: "Submission.toString (1+1)"
java: "Submission.toString(1+1)"
javascript: "submission.toString(1+1)"
kotlin: "toString(1+1)"
python: "submission.to_string(1+1)"
csharp: "Submission.toString(1+1)"
return: "2"
```
> Support language-specific literals

- tested/dsl/schema.json
- tested/dsl/translate_parser.py
- tests/test_dsl_yaml.py
Fixes #406.
This allows an alternative naming scheme for the test hierarchy in the DSL:
1. Units N.S. / Tab O.S.
2. Testcases N.S. / Contexts O.S.
3. Script N.S. / Testcase O.S. (a testcase N.S. has one "script", which consists of a number of elements)
4. Tests (not actually named)
The old / existing names are still supported, and probably will keep being supported: they might be useful for Dodona users, and internally TESTed still uses the Dodona terminology.
> Allow alternative test hierarchy names

- tested/dsl/schema.json
- tested/dsl/schema_draft7.json
- tested/dsl/translate_parser.py
- tested/judge/evaluation.py
- tested/languages/generation.py
- tested/oracles/exception.py
- tested/oracles/exitcode.py
- tested/oracles/nothing.py
- tested/oracles/programmed.py
- tested/oracles/specific.py
- tested/oracles/text.py
- tested/oracles/value.py
- tested/testsuite.py
- tests/test_dsl_yaml.py
Fixes #422.
In addition, allow specifying files at a higher level, e.g. the tab or context in the DSL.
> Fix linked files and allow propagation

- tested/dsl/schema.json
- tested/dsl/schema_draft7.json
- tested/dsl/translate_parser.py
- tests/exercises/echo-function/evaluation/expected_return_and_got_some.yaml
- tests/exercises/echo-function/evaluation/expected_return_but_got_none.yaml
- tests/exercises/echo-function/evaluation/one-language-literals.yaml
- tests/exercises/echo-function/evaluation/one-nested.yaml
- tests/exercises/global/evaluation/plan.yaml
- tests/exercises/objects/evaluation/missing_key_types.yaml
- tests/exercises/objects/evaluation/no-test.yaml
- tests/test_dsl_yaml.py
Fixes #403.
This changes the DSL to have one attribute for return values: `return`.
Then, to decide how to handle it:
1. If the value is an untagged YAML string; interpret it as the string (Python) representation.
2. If the value is an untagged object; interpret is as the advanced output channel object (for oracles).
3. Else, interpret it as a value, like the current `return` behaviour.
Additionally, it introduces an additional tag, `!v` to explicitly mark a value as a YAML value. Some examples:
- `return: 5` is a value, an int
- `return: [5, "old"]` is a value, a list
- `return: "{5, 5}"` is a string representation, thus a set
- `return: !v "{5, 5}"` is a value, a string
- `return: !int8 5` is a value, an int8
In most cases, this will make the test suites easier, as both statements, …
> Unify return values in DSL

- tested/manual.py
- tested/testsuite.py
Exit codes were set to "ignore" by default, which is not what we want. The default now depends on the position of the testcase (ie. must be ignored in all but the last testcase, in which case it must be 0).
Fixes #432
> Fix non-reported exit code

- tested/judge/collector.py
- tested/judge/core.py
- tested/judge/evaluation.py
- tested/languages/bash/generators.py
- Premature exists resulted in missing test cases within a tab
- Make Bash code more robust against exit statements
> Fix a few bugs

- tested/dsl/schema.json
- tested/dsl/schema_draft7.json
- tested/dsl/translate_parser.py
- tests/test_dsl_yaml.py
This PR enables a new object called `definitions` that can be used to define stuff and use it later:
```yaml
- unit: 'Sum of three cubes'
definitions:
sum_of_three: &sum_of_three
oracle: 'custom_check'
language: 'python'
name: 'sum_of_three_cubes'
file: 'oracle.py'
a_value: &string_value "some string"
testcases:
- stdin: '3'
stdout:
<<: *sum_of_three
data: |
1
1
1
- stdin: '33'
stdout: *string_value
- stdin: '42'
- stdout:
<<: *sum_of_three
data: |
-80538738812075974
80435758145817515
12602123297335631
```
This is done by using three YAML features:
- YAML anchors: this gives a name to a node (with `&name`)
- YAML aliases: this refers to an anchor (with `*name`)
- YAML merge key: this merges one hash with another (`<< *name`)
For example, this below will merge all attributes of the …
> Enable definitions blocks in DSL for YAML anchor/alias/merge

- tested/internationalization/en.yaml
- tested/internationalization/nl.yaml
- tested/judge/evaluation.py
Fixes #436, fixes #342.
- Only add one message when something isn't executed.
- Don't mention internal structures; instead there is now a simple message that "Test(s) were not executed".
Closes #443
> Improve messages for missing values and non-executed contexts

- tested/judge/planning.py
Due to a bad flattening, all (execution) units had index 0, meaning they all tried to use the same folder. In most cases, this isn't a problem, but sometimes it is. Fixed by giving the units a proper index.
This fixes the recent `FileExistsError: [Errno 17] File exists: '/home/runner/workdir/execution_0'` errors.
> Fix bug when using execution unit compilation

- README.md
- tested/cli.py
- tested/manual.py
- tests/manual_utils.py
Add a better way to run TESTed from the command line, by introducing a "CLI" mode:
```console
$ python -m tested.cli --help
usage: cli.py [-h] -e EXERCISE [-s SUBMISSION] [-t TESTSUITE] [-f] [-p PROGRAMMING_LANGUAGE]
Simple CLI for TESTed
options:
-h, --help            show this help message and exit
-e EXERCISE, --exercise EXERCISE
Path to a directory containing an exercise
-s SUBMISSION, --submission SUBMISSION
Path to a submission to evaluate
-t TESTSUITE, --testsuite TESTSUITE
Path to a test suite
-f, --full            If the output should be shown in full (default: false)
-p PROGRAMMING_LANGUAGE, --programming_language PROGRAMMING_LANGUAGE
The programming language to use
additional information: The CLI only looks at a config.json file in the exercise directory. It does not look in …
```
> Add better CLI

- tested/dsl/translate_parser.py
For example, from https://dodona.be/en/submissions/15812470/.
If there is an error and we have the information, show a more "user friendly" error, including the actual line where the error occurred.
Before:
```
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/home/niko/Ontwikkeling/universal-judge/tested/manual.py", line 56, in <module>
run(config, sys.stdout)
File "/home/niko/Ontwikkeling/universal-judge/tested/main.py", line 32, in run
suite = parse_dsl(textual_suite)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/niko/Ontwikkeling/universal-judge/tested/dsl/translate_parser.py", line 595, in parse_dsl
dsl_object = _parse_yaml(dsl_string)
^^^^^^^^^^^^^^^^^^^^^^^
File …
```
> Improve error message for YAML syntax errors

- tested/dsl/schema.json
- tested/dsl/schema_draft7.json
- tested/dsl/translate_parser.py
- tests/exercises/echo-function/evaluation/expected_return_and_got_some.yaml
- tests/exercises/echo-function/evaluation/expected_return_but_got_none.yaml
- tests/exercises/echo-function/evaluation/one-language-literals.yaml
- tests/exercises/echo-function/evaluation/one-nested.yaml
- tests/exercises/global/evaluation/plan.yaml
- tests/exercises/objects/evaluation/missing_key_types.yaml
- tests/exercises/objects/evaluation/no-test.yaml
- tests/test_dsl_yaml.py
YAML strings and objects are now interpreted as literal YAML values by default.
We introduce `!expression` and `!oracle` to "cast" strings and objects to expressions and oracles respectively. The list of arguments in an oracle uses the same logic: YAML types by default, expressions when tagged as such.
Using the same logic for arguments is not that obvious: we could also force the use of the expression syntax, as we do with actual expressions and statements. However, it felt more natural to be consistent with the return value (which is in the same YAML object) than with the expressions and statements.
This is basically a reversal of the previous behaviour, where strings and objects needed a `!v` tag. This tag has now been removed.
Fixes #447. Related: #427.
Not to be merged until the …
> Update default interpretation of YAML strings and objects

- tested/languages/bash/linter.py
While the docs say row is zero-based, it is not. Additionally, use `json1` instead of the "legacy" `json` output format for Shellcheck.
Fixes #458
> Fix shellcheck line numbers

- tested/languages/python/linter.py
Since https://github.com/pylint-dev/pylint/pull/3554, do_exit has been deprecated, so don't use it any more. Closes #463
> Fix crash in Pylint 3

- tested/languages/bash/config.py
- tested/languages/bash/generators.py
- tested/languages/config.py
- tested/languages/conventionalize.py
- tested/languages/javascript/generators.py
- tests/test_stacktrace_cleaners.py
This makes Bash more in line with other languages (as we pass the `$0` argument there manually, also without extension).
Fixes #467
> Don't use .sh extension for Bash submission

- tested/languages/bash/linter.py
Partially reverts #460, as Dodona is indeed zero-based.
> Revert to zero-based for annotations

- tested/dsl/schema.json
- tested/dsl/schema_draft7.json
The JSON Schema allowed things that we don't actually allow.
> Improve JSON Schema to return better error message

- tested/judge/evaluation.py
- tested/languages/bash/generators.py
- tested/languages/javascript/generators.py
- tested/languages/python/generators.py
- tests/exercises/echo-function/evaluation/two.yaml
- tests/exercises/echo-function/solution/top-level-output.js
- tests/exercises/echo-function/solution/top-level-output.py
- tests/exercises/echo-function/solution/top-level-output.sh
- tests/test_functionality.py
This resulted in weird output where the testcases were not displayed in the correct testcase.
> Fix bug where output was not caught when importing

- tested/judge/planning.py
- tested/judge/utils.py
When a timeout occurs, we catch the exception and attempt to recover existing stdout/stderr. However, the [docs](https://docs.python.org/3/library/subprocess.html#subprocess.TimeoutExpired) specify that these are `bytes`, even if `text=True`.
We must therefore properly decode these bytes instead of just passing them to `str`.
Fixes #476.
> Fix bug for stdout/stderrr on timeouts

- tested/languages/bash/generators.py
- tested/languages/generation.py
- tests/test_functionality.py
Instead of using `shlex.quote` and then manually joining commands, use `shlex.join`, which has better results, especially for flags and other options.
Fix #480.
> Better escape command line arguments

- tested/dsl/translate_parser.py
- tested/languages/generation.py
- tests/test_dsl_yaml.py
- tests/test_functionality.py
Currently, we just add the stdin below the command that is executed, which is not clear at all. We now use here-doc to display stdin in that case.
If only stdin is used, nothing changes: only stdin is shown.
It looks like this:
The colouring is sometimes a bit wonky, both Rouge and Pygments are not that good at highlighting here-docs.
Fixes #484.
> Use here-doc for stdin if both stdin and arguments are used

- tested/dsl/schema.json
- tested/dsl/schema_draft7.json
- tested/dsl/translate_parser.py
- tested/judge/planning.py
- tested/oracles/text.py
- tests/exercises/echo/evaluation/full.tson
- tests/exercises/echo/evaluation/one.tson
- tests/exercises/echo/evaluation/two.tson
- tests/exercises/echo/solution/correct.cs
- tests/exercises/echo/solution/correct.js
- tests/exercises/sum/evaluation/plan.tson
- tests/exercises/sum/evaluation/short.tson
- tests/exercises/sum/solution/correct.c
- tests/exercises/sum/solution/correct.py
- tests/test_dsl_yaml.py
- tests/test_oracles.py
- Text is now checked strictly be default: there must be an exact match.
- The option `ignoreWhitespace` is still present and can be used to revert to the current behaviour if needed.
- By default, we ensure that the expected values for stdout/stderr in the DSL end with a newline.
- We only add a newline if there is none.
- This can be disabled by setting `normalizeTrailingNewlines` to false.
- We also apply this when using custom oracles.
- We don't do this for JSON test suites, so those should be updated (but apart from a few non-used exercises from us, no one uses the JSON test suites, so I don't think this is a problem).
Fixes #462.
> Enable strict text checking by default

- tested/languages/bash/config.py
- tests/test_stacktrace_cleaners.py
I should have probably looked up the translation instead of just using one.
Fixes #492.
> Fix line linking for Bash (in English)

- README.md
- tested/cli.py
This pull request Fixes some minor issues with the CLI interface as well as adds the new options to have it output verbosely or even at a debug level.
Additionally the changes in the pull request came from the need to use a custom oracle which did not seem to work at all as how the docs described it. As a result I have fixed the classes defined in the documentation (and the one also not there) now properly being available in the scope of the custom oracle function so they can be used to nicely return a result and messages.
Additional to this pull request there is a pull request [dodona-edu/dodona-edu.github.io #396](https://github.com/dodona-edu/dodona-edu.github.io/pull/396) to fix the documentation on this subject as the examples and explanation for creating a custom oracle are wrong or …
> Minor fixes+additions to CLI + fixes to custom_check oracle

- tested/dsl/translate_parser.py
- tests/test_dsl_yaml.py
When updating the documentation, it occurred to me that we currently also append newlines to empty strings for stdout/stderr. This is probably not what we want (since an empty stdout/stderr is perfectly fine), and also not how POSIX defines a file (zero or more lines).
> Do not add newlines to empty strings

- tested/features.py
- tested/judge/core.py
The check was too strict for reduced types. Additionally, add better error messages when this happens, no need to keep useful information to ourselves.
> Fix bug in set type check

- tested/datatypes/__init__.py
- tested/datatypes/advanced.py
- tested/features.py
- tested/languages/config.py
- tested/languages/csharp/config.py
- tested/languages/csharp/templates/Values.cs
- tested/languages/java/config.py
- tested/languages/java/templates/Values.java
- tested/languages/javascript/config.py
- tested/languages/javascript/generators.py
- tested/languages/javascript/templates/values.js
- tested/languages/kotlin/config.py
- tested/languages/kotlin/templates/Values.kt
- tested/languages/python/config.py
- tested/languages/python/templates/values.py
- tests/exercises/objects/evaluation/advanced_values_in_set.yaml
- tests/exercises/objects/evaluation/missing_key_types_js_dictionary.yaml
- tests/exercises/objects/evaluation/missing_key_types_js_object.yaml
- tests/exercises/objects/solution/correct.java
- tests/exercises/objects/solution/correct.js
- tests/test_dsl_expression.py
- tests/test_functionality.py
- tests/test_serialisation.py
Switch to Map by default and introduce two new advanced types to make the distinction between Map/Object when needed. The new types are `dictionary` (since `map` is already in use) for the data structure and `object` for the JavaScript-specific `Object` type, which no other language natively supports at the moment.
All existing languages have been updated to support the `dictionary` advanced type if they supported the basic `map` type, while the advanced type for `object` is reduced, except in JavaScript, which supports both.
As part of this, the way to indicate type limits on certain elements of collections has been reworked to be more flexible. It is now possible to specify limits for all types separately. At the moment, we still only recognise limits on map keys and set elements, so …
> Improve JavaScript handling of Map/Object

- tested/dsl/ast_translator.py
- tested/languages/bash/generators.py
- tested/languages/c/generators.py
- tested/languages/csharp/generators.py
- tested/languages/generation.py
- tested/languages/haskell/generators.py
- tested/languages/java/generators.py
- tested/languages/javascript/generators.py
- tested/languages/kotlin/generators.py
- tested/languages/preparation.py
- tested/languages/python/generators.py
- tested/serialisation.py
- tests/exercises/objects/evaluation/property_assignment.yaml
- tests/exercises/objects/solution/correct.cs
- tests/exercises/objects/solution/correct.java
- tests/exercises/objects/solution/correct.kt
- tests/test_dsl_expression.py
- tests/test_dsl_yaml.py
- tests/test_functionality.py
For example:
```python
instance = Object()
instance.prop = 56
```
Most of the infrastructure to support this was already in place since we support reading properties, and we already support assignments.
Using this requires languages to support both object-orientation and assignments (so e.g. C structs are out).
Fixes #500
> Add support for property/attribute assignment

- tested/dsl/schema-strict.json
- tested/dsl/schema.json
- tested/dsl/translate_parser.py
- tested/oracles/common.py
- tested/oracles/programmed.py
- tested/testsuite.py
- tests/exercises/lotto/evaluation/evaluator.py
- tests/exercises/lotto/evaluation/one-programmed-analysis-correct.yaml
- tests/exercises/lotto/evaluation/one-programmed-analysis-without-language.yaml
- tests/exercises/lotto/evaluation/one-programmed-analysis-wrong.yaml
- tests/test_oracles_builtin.py
- tests/test_oracles_programmed.py
This is a small change/experiment:
- allowing limiting which languages a custom check oracle supports
- if this list of languages is present, pass the location of the source code to the custom check functions of the programmed oracles.
The intended use of this would be to provide a semi-supported way of doing static analysis of the code of the submission. The reasons for doing this are:
- We do have demand for this (and other, proper, solutions is long-term research: #392 )
- We do not have to point people wanting to do this to the Python judge if this is implemented.
- The maintenance burden and backwards compatibility story for us is very minimal: we just pass the path to the submission in the oracle context. We are not committing to allowing static checks specifically.
An alternative, …
> Pass location of source code in oracle context

- .editorconfig
- tested/dsl/schema-strict.json
- tested/dsl/schema.json
- tested/dsl/translate_parser.py
- tested/languages/preparation.py
- tested/testsuite.py
- tests/exercises/echo-function/evaluation/Evaluator.cs
- tests/exercises/echo-function/evaluation/Evaluator.hs
- tests/exercises/echo-function/evaluation/Evaluator.java
- tests/exercises/echo-function/evaluation/Evaluator.kt
- tests/exercises/echo-function/evaluation/evaluator.c
- tests/exercises/echo-function/evaluation/evaluator.js
- tests/exercises/echo-function/evaluation/evaluator.py
- tests/exercises/echo-function/evaluation/one-specific-argument.tson
- tests/exercises/echo-function/evaluation/one-specific-argument.yaml
- tests/test_dsl_yaml.py
- tests/test_oracles_specific.py
In addition to support in the DSL, this adds support for adding arguments to the function call in the test suite.
> Support language-specific evaluators in DSL

- tested/dsl/schema-strict.json
- tested/dsl/schema.json
- tested/dsl/translate_parser.py
- tested/utils.py
- tests/test_dsl_yaml.py
#441 enabled re-using parts of a test suite by using YAML anchors, aliases and merge keys. It also removed our own inheritance support for config options, as using this inheritance means there is no way of specifying "ignore". For example, if a tab has a config option for stdout, it will be inherited by all testcases inside the tab, unless you explicitly override it.
While at the time, the idea was that this would be confusing sometimes, it does cover the most common case of "apply this config to everything". Therefore, this PR re-adds the support.
The means specifically that the following test suite will work as expected:
```yaml
- tab: "echo"
config:
stdout:
normalizeTrailingNewlines: False
testcases:
- expression: 'echo("Hello world!")'
stdout: 'Hello world!'
- expression: 'echo(42)' …
```
> Re-add config inheritance

- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/integration.yml
This allows adding a label to run tests on external pull requests.
This could be a security risks, so only run tests after reviewing the code.
see https://stackoverflow.com/questions/76952023/how-to-make-github-actions-safely-access-secrets-for-prs-created-from-forks
> Allow running tests on external forks after labeling

- tests/test_functionality.py
Currently all languages supported by TESTed have support for the global variables construct.
This PR is part of an effort to add Nextflow support to TESTed.
> Skip tests that require global variables for languages that don't support them

- tested/oracles/value.py
- tests/test_oracles_builtin.py
This issue seemed familiar to me, but I never pushed the fix apparently.
Fixes #562.
> Fix empty map being accepted

- tested/languages/typescript/generators.py
- tests/test_language_quircks.py
- tests/test_problem_statements.py
> Add types for typescript

- tested/dsl/translate_parser.py
- tests/test_dsl_yaml.py
This pr disables validation of `tested-dsl-expression`  if the programming language is specified in the root.
If a programming language is specified in the root, statements and expressions are not parsed and thus don't need to match the validation.
This is a different solution than the one proposed in: https://github.com/dodona-edu/universal-judge/issues/578
The main difference is that the proposed solution told the schema that in case a programming language is specified the format is not required. While in my solution, the schema still 'requires' the format, but the validation of this format becomes more flexible in case the root language is specified.
I chose this second option as this had a way smaller impact on the code, and the validation of the format happened in custom python code …
> Fix global definition of programming language
